AWSTemplateFormatVersion: 2010-09-09
Description: This template is a base CloudFormation Template for generating resources
Metadata:
  Authors: Caleb Wallace
  Description: >-
    2024-11-19, this template is a generic starting point for generating CloudFormation templates.
    Parameters are in alphabetical order, separated into the following sections:
    - Utility Parameters
    - Tagging Parameters
    
    Parameter attributes are ordered as follows: Description, Type, Default, (optional) AllowedValues/Patterns, Constraints, etc.

Parameters:
  # Utility Parameters
  VPCBaseCIDRblock:
    Description: CIDR Block for Base VPC network
    Type: String
    Default: 10.0.0.0/16
    AllowedPattern: ^(1\d{1,2}|2[0-4]\d|25[0-5]|\d{1,2})\.(1\d{1,2}|2[0-4]\d|25[0-5]|\d{1,2})\.(1\d{1,2}|2[0-4]\d|25[0-5]|\d{1,2})\.(1\d{1,2}|2[0-4]\d|25[0-5]|\d{1,2})\/([1-9]|[12]\d|3[0-2])$
  VPCBaseEnableDnsHostnames:
    Description: Enable DNS hostnames for Base VPC network
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  VPCEnableDnsSupport:
    Description: Enable DNS support for Base VPC network
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  VPCInstanceTenancy:
    Description: Instance tenancy for Base VPC network
    Type: String
    Default: default
    AllowedValues:
      - default
      - dedicated
  VPCAdminSubnetCIDRbits:
    Description: Number of CIDR bits needed to populate AWS Admin Subnet (maximum 8 = 253 hosts, default 4 = 14 hosts)
    Type: Number
    Default: 4
  VPCManagementSubnetCIDRbits:
    Description: Number of CIDR bits needed to populate Management Subnet (maximum 8 = 253 hosts, default 4 = 14 hosts)
    Type: Number
    Default: 4
  VPCMarketingSubnetCIDRbits:
    Description: Number of CIDR bits needed to populate Marketing Subnet (maximum 8 = 253 hosts, default 4 = 14 hosts)
    Type: Number
    Default: 4
  VPCDevelopmentSubnetCIDRbits:
    Description: Number of CIDR bits needed to populate Development Subnet (maximum 8 = 253 hosts, default 6 = 62 hosts)
    Type: Number
    Default: 6

  # Tagging Parameters
  VPCBaseNetworkName:
    Description: Name of Base VPC network
    Type: String
    Default: net0
  VPCAdminSubnetName:
    Description: Name of AWS Admin Subnet
    Type: String
    Default: admin-subnet
  VPCManagementSubnetName:
    Description: Name of Management Subnet
    Type: String
    Default: management-subnet
  VPCMarketingSubnetName:
    Description: Name of Marketing Subnet
    Type: String
    Default: marketing-subnet
  VPCDevelopmentSubnetName:
    Description: Name of Development Subnet
    Type: String
    Default: development-subnet

    
Resources:
  VPCBaseNetwork:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCBaseCIDRblock
      EnableDnsHostnames: !Ref VPCBaseEnableDnsHostnames
      EnableDnsSupport: !Ref VPCEnableDnsSupport
      InstanceTenancy: !Ref VPCInstanceTenancy
      Tags:
        - Key: Name
          Value: !Ref VPCBaseNetworkName

  VPCAdminSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCBaseNetwork
      CidrBlock: !Select
        - 0
        - !Cidr
          - !GetAtt VPCBaseNetwork.CidrBlock
          - 1
          - !Ref VPCAdminSubnetCIDRbits
    DependsOn: VPCBaseNetwork
  
  

Outputs:
  # Base Network Outputs
  VPCBaseNetworkARN:
    Description: Amazon Resource Number assigned to Base VPC Network.
    Value: !GetAtt VPCBaseNetwork.Arn
  VPCBaseNetworkCIDR:
    Description: The resulting CIDR block assigned to Base VPC Network.
    Value: !GetAtt VPCBaseNetwork.CidrBlock

  # Admin Subnet Outputs
  VPCAdminSubnetARN:
    Description: Amazon Resource Number assigned to Admin Subnet.
    Value: !GetAtt VPCAdminSubnet.Arn
  VPCAdminSubnetCIDR:
    Description: The resulting CIDR block assigned to Admin Subnet.
    Value: !GetAtt VPCAdminSubnet.CidrBlock